In [ ]:
# Customer churn with Logistic Regression
#A telecommunications company is concerned about the number of customers leaving their land-line business for cable competitors.
# They need to understand who is leaving. 
# Imagine that you are an analyst at this company and you have to find out who is leaving and why.

In [ ]:
# About the dataset
#Data pre-processing and selection
#Modeling (Logistic Regression with Scikit-learn)
#Evaluation
# Practice

In [5]:
# import libraries: 
import pandas as pd
import numpy as np
import pylab as pl
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline
import matplotlib.pyplot as plt

In [7]:
# get data 
path= "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/ChurnData.csv"
df=pd.read_csv(path)
df.head( 10)

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
5    68.0  52.0     17.0   120.0  1.0    24.0    0.0       1.0       0.0   
6    42.0  40.0      7.0    37.0  2.0     8.0    1.0       1.0       1.0   
7     9.0  21.0      1.0    17.0  2.0     2.0    0.0       0.0       0.0   
8    35.0  50.0     26.0   140.0  2.0    21.0    0.0       1.0       0.0   
9    49.0  51.0     27.0    63.0  4.0    19.0    0.0       1.0       0.0   

   longmon  ...    pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...      1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...      0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...      0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...      1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...      0.0       0.0       1.0     1.0    0.0    1.960    3.091   
5    20.70  ...      0.0       0.0       0.0     0.0    0.0    3.030    3.240   
6     8.25  ...      0.0       1.0       1.0     1.0    1.0    2.110    3.157   
7     2.90  ...      0.0       0.0       0.0     0.0    0.0    1.065    3.240   
8     6.50  ...      0.0       0.0       1.0     1.0    0.0    1.872    3.314   
9    12.85  ...      0.0       1.0       1.0     0.0    1.0    2.553    3.248   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  
5  4.787      1.0    0.0  
6  3.611      4.0    0.0  
7  2.833      1.0    0.0  
8  4.942      3.0    0.0  
9  4.143      2.0    0.0  

[10 rows x 28 columns]

In [ ]:
# Data pre-processing and selection
# Lets select some features for the modeling. Also we change the target data type to be integer, as it is a requirement by the skitlearn algorithm:

In [8]:
df=df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
df['churn']=df['churn'].astype('int')
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   churn  
0      1  
1      1  
2      0  
3      0  
4      0

In [9]:
df.shape

(200, 10)

In [10]:
df['churn'].shape

(200,)

In [15]:
# Change data frame to numpy array to X and y for modeling and prediction

X=df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']].values
X[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])

In [16]:
# or use  np.asarray
X=np.asarray(df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
X[0:5] # index with [0:5] first row to 4th row


array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])

In [17]:
y= np.asarray(df['churn'])
y[0:5]

array([1, 1, 0, 0, 0])

In [18]:
# we normalize the dataset X using preprocessing.StandardScaler().fit(X).transform(X)
X= preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])

In [19]:
# Train/Test dataset with train_test_split
from sklearn.model_selection import train_test_split

# Create  train and test data

x_train, x_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state= 4)
print( " Train data is: ", x_train.shape, y_train.shape)
print(" Test Data is: ", x_test.shape, y_test.shape)

 Train data is:  (160, 7) (160,)
 Test Data is:  (40, 7) (40,)


In [29]:
y_test

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [20]:
# Modeling (Logistic Regression with Scikit-learn)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(x_train,y_train)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [25]:
yhat = LR.predict(x_test)
yhat

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [27]:
# Now we can predict using our test set:
yhat_proba=LR.predict_proba(x_test)
yhat_proba

array([[0.54132919, 0.45867081],
       [0.60593357, 0.39406643],
       [0.56277713, 0.43722287],
       [0.63432489, 0.36567511],
       [0.56431839, 0.43568161],
       [0.55386646, 0.44613354],
       [0.52237207, 0.47762793],
       [0.60514349, 0.39485651],
       [0.41069572, 0.58930428],
       [0.6333873 , 0.3666127 ],
       [0.58068791, 0.41931209],
       [0.62768628, 0.37231372],
       [0.47559883, 0.52440117],
       [0.4267593 , 0.5732407 ],
       [0.66172417, 0.33827583],
       [0.55092315, 0.44907685],
       [0.51749946, 0.48250054],
       [0.485743  , 0.514257  ],
       [0.49011451, 0.50988549],
       [0.52423349, 0.47576651],
       [0.61619519, 0.38380481],
       [0.52696302, 0.47303698],
       [0.63957168, 0.36042832],
       [0.52205164, 0.47794836],
       [0.50572852, 0.49427148],
       [0.70706202, 0.29293798],
       [0.55266286, 0.44733714],
       [0.52271594, 0.47728406],
       [0.51638863, 0.48361137],
       [0.71331391, 0.28668609],
       [0.

In [ ]:
# predict_proba returns estimates for all classes, ordered by the label of classes.
# So, the first column is the probability of class 1, P(Y=1|X),
# and second column is probability of class 0, P(Y=0|X):

In [ ]:
# Evaluation

In [ ]:
# jaccard index
# Lets try jaccard index for accuracy evaluation. we can define jaccard as
# the size of the intersection divided by the size of the union of two label sets. 
# If the entire set of predicted labels for a sample strictly match with the true set of labels,
# then the subset accuracy is 1.0; otherwise it is 0.0.

In [30]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, yhat)

ValueError: Classification metrics can't handle a mix of binary and continuous-multioutput targets

In [ ]:
# confusion matrix
# Another way of looking at accuracy of classifier is to look at confusion matrix.

In [31]:
from sklearn.metrics import classification_report, confusion_matrix
import itertools
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')
print(confusion_matrix(y_test, yhat, labels=[1,0]))

ValueError: Classification metrics can't handle a mix of binary and continuous-multioutput targets

In [32]:
print (classification_report(y_test, yhat))

ValueError: Classification metrics can't handle a mix of binary and continuous-multioutput targets