In [ ]:
#  numpy.arange
#numpy.arange([start value, stop value), [step, ], dtype=None)
#Return evenly spaced values within a given interval.

#Values are generated within the half-open interval [start, stop) (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

# When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use numpy.linspace for these cases.

In [ ]:
#Parameters:	
#start : number, optional
#Start of interval. The interval includes this value. The default start value is 0.

#stop : number
#End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

#step : number, optional
#Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.

#dtype : dtype
#The type of the output array. If dtype is not given, infer the data type from the other input arguments.

#Returns:	
#arange : ndarray
#Array of evenly spaced values.

#For floating point arguments, the length of the result is ceil((stop - start)/step). Because of floating point overflow, this rule may result in the last element of out being greater than stop.

In [2]:
import numpy as np
# Example of np.arrange( )
np.arange(3)  # same as np.arrange(0,3,1) # Start value default 0, step value deault 1


array([0, 1, 2])

In [4]:

np.arange(3.0)  # np.arrange( 0.0, 3.0, 1)


array([0., 1., 2.])

In [5]:

np.arange(3,7) # np.arrange(3,7,1)


array([3, 4, 5, 6])

In [7]:

np.arange(3,7,2)  # start value is 3, end value is 7 and step value is 2 
# array([3, 5])

array([3, 5])